### Day Objectives:
- Maps

- Lambda

- Filter

- Use cases - File/Data Encryption

### Map


Mapping - Entity with Function

f : x^2 

x : [1,5]

f(x) 

y=f(x)=x^2

x    y

1    1

2    4

3    9

4    16 

5    25



map(function,Iterable)




In [3]:
def powerN(a,n):
    #return a**n
    r=1
    for i in range(0,n):
        r *= a
    return r
powerN(2,10)
     
    
def recursivepowerN(a,n):
    if n==0:
        return 1
    else:
        return a*recursivepowerN(a,n-1)
recursivepowerN(2,10)



1024

In [20]:
def cube(n):
    return n**3

li=[1,2,3,4,5,6]

set(map(cube,li))
set(map(cube,[12]))

#li=['1','2','3','4']
li1=list(map(int,li))
li2=list(map(str,li1))


tuple(map(float,li))

numbers=[int(i) for i in li]
[cube(i) for i in numbers]

[1, 8, 27, 64, 125, 216]

### Filter

Used to check boolean values



In [15]:
li=[1,2,3,4,'a','s','i',9]

def isdigit(c):
    c=str(c)
    if c.isdigit():
        return False
    return True
isdigit('1')
list(filter(isdigit,li))

['a', 's', 'i']

In [31]:
# Identify all Primes in a range

def checkPrime(c):
    d=0
    for i in range(1,c+1):
        if c%i==0:
            d+=1
    if d==2:
        return True
    else:
        return False
checkPrime(5)

#x=[1,2,3,4,5,6,7,8,9,10]            
list(filter(checkPrime,[1,2,3,4,5,6,7,8,9,10]))  
            

[2, 3, 5, 7]

In [28]:
def rangePrimes(n):
    l=[]
    for i in range(0,n):
        if checkPrime(i):
            l.append(i)
    return l
rangePrimes(10)
            

[2, 3, 5, 7]

In [21]:
def isprime(n):
    if n<2:
        return False
    for i in range(2,n//2+1):
        if n%i==0:
            return False
    return True
lb,ub=65,122
Primeslist=list(filter(isprime,range(lb,ub)))
print(Primeslist)
Primelist=[i for i in range(lb,ub+1) if isprime(i)]
print(Primelist)

# Map fails because it doesn't apply for checking conditins

[67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113]
[67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113]


### Lambda

Anonymous Functions

Can be embedded into List Comprehensions,Maps,Filters


In [32]:
a=lambda x: x**3 
#a(3)

list(map(lambda x:x**3 ,[1,2,3,4,5]))

list(filter(lambda x:(x%2==0),[1,2,3,4,5,6,7,8]))



[2, 4, 6, 8]

In [41]:
from random import randint

internal1=[randint(0,25) for i in range(10)]
internal2=[randint(0,25) for i in range(10)]
externl=[randint(0,75) for i in range(10)]
averageInternal=list(map(lambda x,y: (x+y)//2, internal1,internal2))
print(averageInternal)
failedmarks=list(filter(lambda x:x<15, averageInternal))
print(failedmarks)

[22, 15, 16, 23, 8, 16, 8, 7, 22, 12]
[8, 8, 7, 12]


### Applying functional programming to the marks analysis application



In [5]:
# Generate Marks data
from random import randint

def generateMarks(n,lb,ub):
    filename='marks.txt'
    with open(filename, 'w') as f:
        for i in range(n):
            marks=randint(lb,ub)
            f.write(str(marks)+'\n')
            
generateMarks(100,0,100)
        

In [9]:
# Marks Analysis
    # Class Average, % of Passed,Failed and distinction,Frequency of highest and lowest marks
def readMarkslist(filepath):
    with open(filepath,'r') as f:
        filedata=f.read().split()
        #markslist=re.split('\n',filedata)
    return list(map(int,filedata))
filepath='marks.txt'
readMarkslist(filepath)

    
    
def classavg(filepath):
    markslist=readMarkslist(filepath)
    return sum(markslist)//len(markslist)
filepath='marks.txt'
classavg(filepath)

46

In [10]:
# Failed percentage

def PercentageFailed(filepath):
    markslist=readMarkslist(filepath)
    failedcount=len(list(filter(lambda x:x<40, markslist)))
    return (failedcount*100)/len(markslist)
PercentageFailed(filepath)

45.0

In [11]:
def Percentagepassed(filepath):
    return 100-PercentageFailed(filepath)
Percentagepassed(filepath)

55.0

In [12]:
def distinction(filepath):
    markslist=readMarkslist(filepath)
    distinction=len(list(filter(lambda x:x>=70, markslist)))
    return (distinction/len(markslist))*100
distinction(filepath)

27.0

In [13]:
def  highestmarkFrequency(filepath):
    markslist=readMarkslist(filepath)
    return markslist.count(max(markslist)),max(markslist)
highestmarkFrequency(filepath)

(2, 98)

In [16]:
def  lowestmarkFrequency(filepath):
    markslist=readMarkslist(filepath)
    return markslist.count(min(markslist)),min(markslist)
lowestmarkFrequency(filepath)

(2, 1)

### Data Encryption


key - Mapping of data/charecters with replaced charecter

0 -> 4

1 -> 5

2 -> 6

3 -> 7

4 -> 8

5 -> 9

6 -> 0

7 -> 1

8 -> 2

9 -> 3

In [20]:
# Function to generate key for encryption
keypath='key.txt'
def generateKey(keypath):
    with open(keypath,'w') as f:
        for i in range(10):
            if i<6:
                f.write(str(i)+ ' '+str(i+4)+'\n')
            else:
                 f.write(str(i)+ ' '+str(i-6)+'\n')
    return
generateKey(keypath)
                    
    

In [2]:
# Function to encrypt a data file

keyfile='key.txt'
def dictionaryKeyFile(keyfile):
    key={}
    with open(keyfile,'r') as f:
        #line=f.readline().split()
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
    return key
#dictionaryKeyFile(keyfile)


def encryptMarksData(datafile,keyfile):
    #construct a dictionary for key data
    key=dictionaryKeyFile(keyfile)
    with open(datafile,'r') as f:
        filedata=f.read().split('\n')
    with open('untitled.txt','w') as f:
        for mark in filedata:
            line =' '
            for n in mark:
                line+=key[n]
            f.write(line+'\n')
    return
datafile='marks.txt'
encryptMarksData(datafile,keyfile)

    
    

In [15]:
def decryptmarksData(encryptedFile, kayfile):
    key=dictionaryKeyFile(keyfile)
    newkey={}
    for key,value in key.items():
        newkey[value]=key
    with open(encryptedfile,'r') as f:
        encrypteddata=f.read().split('\n')
        
    with open('decryptedMarks.txt','w') as f:
        
        

SyntaxError: unexpected EOF while parsing (<ipython-input-15-1699538f978c>, line 11)

In [7]:
keyfile='key.txt'
key=dictionaryKeyFile(keyfile)
evenkeys={iteam for iteam in key }
evenkeys

NameError: name 'dictionaryKeyFile' is not defined

In [8]:
## N


In [14]:
import numpy as np
li=[1,2,3,4,5]
a=np.array(li)
a
b=np.arange(15)#a,range=arange
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
m=np.random.randint(0,9,size=(3,3))
print(m)
print(m[0][0])


[[5 1 3]
 [5 6 0]
 [2 1 8]]
5


In [29]:
m=np.random.randint(0,9,size=(3,3,3))
print(m)

[[[1 2 7]
  [5 5 0]
  [6 1 2]]

 [[5 4 4]
  [2 2 4]
  [8 6 1]]

 [[0 2 4]
  [2 0 2]
  [3 1 2]]]


In [32]:
m=np.random.randint(0,9,size=(3,3,3,3))
print(m)
m[2][2][2][1]

[[[[1 5 3]
   [1 7 8]
   [7 5 2]]

  [[5 5 3]
   [6 8 0]
   [0 2 8]]

  [[5 3 2]
   [7 6 2]
   [0 6 0]]]


 [[[6 4 0]
   [8 0 8]
   [0 1 8]]

  [[3 3 2]
   [0 6 3]
   [4 1 3]]

  [[2 1 4]
   [3 0 8]
   [5 4 2]]]


 [[[1 1 4]
   [8 3 3]
   [2 5 3]]

  [[6 5 0]
   [0 6 2]
   [6 5 6]]

  [[0 7 0]
   [6 5 7]
   [1 8 3]]]]


8

In [46]:
m.ndim
m.size
m.shape
m.dtype
mitemsize

NameError: name 'mitemsize' is not defined

In [41]:
k=np.random.randint(0,9,size=(3,4))
k

array([[7, 0, 0, 5],
       [2, 4, 2, 1],
       [1, 8, 3, 0]])

In [42]:
k[:2,:3]

array([[7, 0, 0],
       [2, 4, 2]])

In [43]:
k[:3,::2]

array([[7, 0],
       [2, 2],
       [1, 3]])

In [44]:
k[::-1,::-1]

array([[0, 3, 8, 1],
       [1, 2, 4, 2],
       [5, 0, 0, 7]])

In [63]:
k=np.random.randint(1,9,size=(3,3))
print(k)
k.T()
k
#k[::-1,::-1]

[[5 8 1]
 [7 3 8]
 [1 4 6]]


TypeError: 'numpy.ndarray' object is not callable

## Pandas
- Data Cleaning
- Data transformation
- Data Analysis

## Notations
- Series
- DataFrames

In [5]:
import pandas as pd

internal1={'s1':21,'s2':18,'s3':7}
internal1=pd.Series(internal1)
internal1
internal2={'s1':15,'s2':20,'s4':20}
internal2=pd.Series(internal2)
internal2


s1    15
s2    20
s4    20
dtype: int64

In [6]:
final={'Internal1':internal1,'Internal':internal2}
final=pd.DataFrame(final)
final

Internal1  Internal
s1       21.0      15.0
s2       18.0      20.0
s3        7.0       NaN
s4        NaN      20.0

In [71]:
final={'Internal1':internal1,'Internal':internal2}
final=pd.DataFrame(final)
final['Internal1']

s1    21.0
s2    18.0
s3     7.0
s4     NaN
Name: Internal1, dtype: float64

In [73]:
final.keys

<bound method NDFrame.keys of     Internal1  Internal
s1       21.0      15.0
s2       18.0      20.0
s3        7.0       NaN
s4        NaN      20.0>

In [76]:
final.columns

Index(['Internal1', 'Internal'], dtype='object')

In [78]:
final.values

array([[21., 15.],
       [18., 20.],
       [ 7., nan],
       [nan, 20.]])

In [80]:
final.values[1]

array([18., 20.])

In [81]:
final.values[2][0]

7.0

In [13]:
for row in final.values:
    print('Internal1 -' ,+row[0],'Internal2 -'+row[1])

TypeError: can only concatenate str (not "numpy.float64") to str

In [90]:
final.loc['s5']=[22,29]
final

Internal1  Internal
s1       21.0      15.0
s2       18.0      20.0
s3        7.0       NaN
s4        NaN      20.0
s5       22.0      29.0

In [11]:
final.drop(5)
final

KeyError: '[5] not found in axis'

In [10]:
final.values[2]=[13,19]
final

Internal1  Internal
s1       21.0      15.0
s2       18.0      20.0
s3       13.0      19.0
s4        NaN      20.0

In [15]:
# Reading CSV file data
import pandas as pd
filepath='income.csv'
l=pd.read_csv(filepath)
l


GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [23]:
for row in l.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [18]:
sum=0
for i in range(2,11):
    sum +=l.values[2][i]
sum/len(l.values[2][2:])

47214.77777777778

In [22]:
sum=0
for row in l.values:
    sum+=row[-2]
sum/len(l.values)

50038.8